import js from '@eslint/js'
import vue from 'eslint-plugin-vue'
import tseslint from 'typescript-eslint'

/**
 * The first linter this repository has had.
 *
 * Sixty thousand lines of TypeScript, four `package.json` files and no `lint`
 * script anywhere: CI typechecked and tested, and nothing else read the code.
 * That absence is visible in the findings this config was added alongside — an
 * exported function with no caller, an import that should have been used, the
 * same filter spelled `{}` in two copies of a function and `undefined` in a
 * third, a shared type re-spelled inline in one of two controllers.
 *
 * **Deliberately a small, curated rule set rather than the full recommended
 * one.** A config that reports two thousand problems on its first run gets the
 * job deleted rather than the code fixed. Everything enabled here is either
 * already clean or nearly so, which is what makes `npm run lint` a signal
 * instead of a wall. Turning more on later is a small commit; turning a red
 * build off is a habit.
 *
 * Type-aware rules (`recommendedTypeChecked`) are not enabled: they need a
 * program per tsconfig and are markedly slower, and `npm run typecheck` already
 * covers what they would catch. This is for the things the compiler is happy to
 * allow.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.nuxt/**',
      '**/.output/**',
      // Generated by `prisma generate`, and neither ours to fix nor small.
      'apps/api/src/prisma/generated/**',
      'apps/web/e2e/.auth/**',
      'apps/web/test-results/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      /*
       * The rule that would have caught `languageNativeName` and `isOpenStatus`
       * — both exported, both called by nothing but their own spec.
       *
       * `argsIgnorePattern` because a leading underscore is already this
       * codebase's convention for a parameter that exists to satisfy a
       * signature: multer's `(_request, file, callback)` cannot drop the first.
       */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],

      /*
       * Off. The codebase uses `any` sparingly and deliberately — mostly at the
       * Prisma and Express boundaries, where the alternative is a cast that says
       * less. Making it an error here would report existing, considered code.
       */
      '@typescript-eslint/no-explicit-any': 'off',

      /*
       * Off for the same reason: `!` appears where a value has already been
       * proven present a line earlier, and the rule cannot see that.
       */
      '@typescript-eslint/no-non-null-assertion': 'off',

      /*
       * A warning, not an error.
       *
       * Attaching `cause` to a rethrown error is a genuine improvement and it
       * changes the shape of what is thrown — `FfmpegError` in particular exists
       * to *drop* the original, because `execFile`'s message leads with the whole
       * command line and shows absolute server paths to an admin. That decision
       * is deliberate and documented, so the rule reports rather than fails.
       */
      'preserve-caught-error': 'warn',
    },
  },

  // Vue single-file components. `vue-eslint-parser` has to own the file and
  // hand the `<script>` block to the TypeScript parser, not the other way round.
  ...vue.configs['flat/recommended'],
  {
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    rules: {
      /*
       * Off: Nuxt auto-imports components, so `<MediaCard />` resolves without an
       * import and the rule cannot know that. Same for the multi-word component
       * rule — the pages are named by their routes.
       */
      'vue/multi-word-component-names': 'off',
      /*
       * Off: attribute order and self-closing style are formatting opinions this
       * repository has never held, and enforcing them now would rewrite every
       * template for no defect caught.
       */
      'vue/attributes-order': 'off',
      'vue/html-self-closing': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',

      /*
       * A warning, not an error.
       *
       * `VideoJobs` and `VideoPlayer` both `defineExpose` after a top-level
       * `await`, and both are called through that exposed handle today — the
       * video editor refreshes the jobs panel with it. The rule is right in
       * general and fixing it means restructuring async setup in two components
       * that work, which is not a change to make blind while landing a linter.
       */
      'vue/no-expose-after-await': 'warn',
    },
  },

  // Node scripts and configs run outside the browser and outside Nuxt's
  // auto-imports, so their globals differ.
  {
    files: ['**/*.config.{js,mjs,ts}', 'apps/api/**/*.ts', 'packages/**/*.ts'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly', Buffer: 'readonly', __dirname: 'readonly' },
    },
  },

  // Jest and Vitest supply their own globals; Nuxt supplies auto-imports that no
  // file declares. Undefined-variable checking is the compiler's job here.
  {
    files: ['**/*.spec.ts', '**/*.db-spec.ts', '**/*.e2e-spec.ts', 'apps/web/**/*.{ts,vue}'],
    rules: { 'no-undef': 'off' },
  },
)
