import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';

import { Logger, type INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';

import { AppModule } from '../src/app.module';
import { SessionStoreService } from '../src/auth/session-store.service';
import { bigIntReplacer } from '../src/common/json';
import { StorageService } from '../src/common/storage.service';
import { FfmpegService } from '../src/media/ffmpeg.service';
import { MediaService } from '../src/media/media.service';
import { PrismaService } from '../src/prisma/prisma.service';

const run = promisify(execFile);

/**
 * Probing and thumbnails against **real ffmpeg** and a real Postgres.
 *
 * Mocking ffmpeg here would test the mock. The files are generated by ffmpeg
 * itself — a second of colour bars encodes in well under a second, so this
 * stays fast while exercising the actual binaries the app shells out to.
 */
describe('Media probing (real ffmpeg)', () => {
  const PASSWORD = 'correct horse battery staple';
  const tokenFile = join(tmpdir(), 'video-streaming-media-test.bootstrap-token');

  let workspace: string;
  let mediaRoot: string;
  let app: INestApplication;
  let prisma: PrismaService;
  let storage: StorageService;
  let media: MediaService;
  let banner: jest.SpyInstance;
  let admin: request.Agent;
  let collectionId: string;

  /** Encodes a real video file with ffmpeg. */
  async function makeVideo(
    relPath: string,
    options: { seconds?: number; size?: string; videoCodec?: string; audioCodec?: string; pixelFormat?: string } = {},
  ): Promise<void> {
    const {
      seconds = 1,
      size = '320x240',
      videoCodec = 'libx264',
      audioCodec = 'aac',
      pixelFormat = 'yuv420p',
    } = options;

    const absolute = join(mediaRoot, relPath);
    await mkdir(dirname(absolute), { recursive: true });

    await run('ffmpeg', [
      '-hide_banner', '-loglevel', 'error', '-y',
      '-f', 'lavfi', '-i', `testsrc=size=${size}:rate=10:duration=${seconds}`,
      '-f', 'lavfi', '-i', `sine=frequency=440:duration=${seconds}`,
      '-c:v', videoCodec, '-pix_fmt', pixelFormat,
      '-c:a', audioCodec,
      '-t', String(seconds),
      absolute,
    ]);
  }

  async function seedVideo(relPath: string, title: string): Promise<string> {
    const { size } = await storage.statOf('media', relPath).then((s) => s ?? { size: 0 });
    const video = await prisma.video.create({
      data: {
        collections: { create: { collectionId } },
        slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        title,
        storageKey: relPath,
        contentTag: `tag-${title}`,
        originalName: relPath,
        mimeType: 'video/mp4',
        sizeBytes: BigInt(size),
        fileMtime: new Date(),
        state: 'DRAFT',
      },
      select: { id: true },
    });
    return video.id;
  }

  async function startApp(): Promise<void> {
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = moduleRef.createNestApplication();
    app.getHttpAdapter().getInstance().set('json replacer', bigIntReplacer);
    app.use(app.get(SessionStoreService).createMiddleware());
    await app.init();
    prisma = app.get(PrismaService);
    storage = app.get(StorageService);
    media = app.get(MediaService);
  }

  beforeAll(async () => {
    // Fail loudly rather than skipping — a green run that probed nothing is worse.
    await run('ffprobe', ['-version']);
  });

  beforeEach(async () => {
    banner = jest.spyOn(Logger.prototype, 'log').mockImplementation(() => undefined);
    workspace = await mkdtemp(join(tmpdir(), 'media-'));
    mediaRoot = join(workspace, 'media');
    await mkdir(mediaRoot, { recursive: true });

    process.env.SESSION_SECRET ??= 'db-spec-secret';
    process.env.BOOTSTRAP_TOKEN_FILE = tokenFile;
    process.env.MEDIA_ROOT = mediaRoot;
    process.env.DERIVED_ROOT = join(workspace, 'derived');
    process.env.INGEST_WATCHER_ENABLED = 'false';
    await rm(tokenFile, { force: true });

    await startApp();
    await prisma.$executeRawUnsafe(
      'TRUNCATE "InviteToken", "User", "session", "Collection", "Season", "Video", "IngestIssue" RESTART IDENTITY CASCADE',
    );
    await app.close();
    await rm(tokenFile, { force: true });

    await startApp();

    admin = request.agent(app.getHttpServer());
    await admin
      .post('/auth/redeem')
      .send({ token: (await readFile(tokenFile, 'utf8')).trim(), username: 'ada', password: PASSWORD })
      .expect(201);

    const collection = await admin.post('/collections').send({ title: 'Films' }).expect(201);
    collectionId = collection.body.id;
  });

  afterEach(async () => {
    banner.mockRestore();
    await app?.close();
    await rm(tokenFile, { force: true });
    await rm(workspace, { recursive: true, force: true });
  });

  describe('probing a real file', () => {
    it('records duration, dimensions and codecs', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 1, size: '640x480' });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      media.enqueue(id);
      await media.drain();

      const video = await prisma.video.findUniqueOrThrow({ where: { id } });
      expect(video.width).toBe(640);
      expect(video.height).toBe(480);
      expect(video.videoCodec).toBe('h264');
      expect(video.audioCodec).toBe('aac');
      expect(video.durationSec).toBeGreaterThan(0.5);
      expect(video.probedAt).not.toBeNull();
      expect(video.probeError).toBeNull();
    });

    it('counts audio tracks, so the UI can warn before a conversion drops them', async () => {
      await makeVideo('Films/bars.mp4');
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      media.enqueue(id);
      await media.drain();

      await expect(prisma.video.findUniqueOrThrow({ where: { id } })).resolves.toMatchObject({
        audioTracks: 1,
      });
    });

    it('leaves an mp4 with h264 and aac alone', async () => {
      await makeVideo('Films/fine.mp4');
      const id = await seedVideo('Films/fine.mp4', 'Fine');

      media.enqueue(id);
      await media.drain();

      await expect(prisma.video.findUniqueOrThrow({ where: { id } })).resolves.toMatchObject({
        needsConversion: false,
      });
    });

    // The case the feature exists for: an MKV plays on almost nothing.
    it('flags an mkv for conversion', async () => {
      await makeVideo('Films/matroska.mkv');
      const id = await seedVideo('Films/matroska.mkv', 'Matroska');

      media.enqueue(id);
      await media.drain();

      await expect(prisma.video.findUniqueOrThrow({ where: { id } })).resolves.toMatchObject({
        needsConversion: true,
      });
    });

    it('flags 10-bit colour, which is what -pix_fmt yuv420p fixes', async () => {
      await makeVideo('Films/tenbit.mp4', { pixelFormat: 'yuv420p10le' });
      const id = await seedVideo('Films/tenbit.mp4', 'Ten Bit');

      media.enqueue(id);
      await media.drain();

      await expect(prisma.video.findUniqueOrThrow({ where: { id } })).resolves.toMatchObject({
        needsConversion: true,
      });
    });

    /**
     * One unreadable file must not stop a scan of two hundred. The error is
     * recorded on the row so the admin sees which file and why.
     */
    it('records a probe failure rather than throwing', async () => {
      await mkdir(join(mediaRoot, 'Films'), { recursive: true });
      await writeFile(join(mediaRoot, 'Films/broken.mp4'), 'this is not a video');
      const id = await seedVideo('Films/broken.mp4', 'Broken');

      await expect(
        (async () => {
          media.enqueue(id);
          await media.drain();
        })(),
      ).resolves.toBeUndefined();

      const video = await prisma.video.findUniqueOrThrow({ where: { id } });
      expect(video.probedAt).not.toBeNull();

      /**
       * The message has to say what is wrong with the file. execFile's own
       * error leads with the whole command line, which would push the diagnosis
       * past the point this column is truncated — and show server paths to an
       * admin who cannot act on them.
       */
      expect(video.probeError).toContain('ffprobe failed');
      expect(video.probeError).toMatch(/moov atom|Invalid data/);
      expect(video.probeError).not.toContain('-show_streams');
      expect(video.probeError).not.toContain(mediaRoot);
    });

    it('keeps going after a failure', async () => {
      await mkdir(join(mediaRoot, 'Films'), { recursive: true });
      await writeFile(join(mediaRoot, 'Films/broken.mp4'), 'not a video');
      await makeVideo('Films/good.mp4');
      const broken = await seedVideo('Films/broken.mp4', 'Broken');
      const good = await seedVideo('Films/good.mp4', 'Good');

      media.enqueue(broken);
      media.enqueue(good);
      await media.drain();

      // The good file is probed despite the broken one queued ahead of it.
      await expect(prisma.video.findUniqueOrThrow({ where: { id: good } })).resolves.toMatchObject({
        probeError: null,
        videoCodec: 'h264',
      });
      await expect(prisma.video.findUniqueOrThrow({ where: { id: broken } })).resolves.toMatchObject({
        probeError: expect.any(String),
      });
    });
  });

  describe('artwork', () => {
    it('generates both shapes automatically after a probe', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      media.enqueue(id);
      await media.drain();

      const video = await prisma.video.findUniqueOrThrow({ where: { id } });

      expect(video.bannerKey).toBe(`thumbnails/${id}.jpg`);
      expect(video.bannerSource).toBe('AUTO');
      await expect(storage.exists('derived', video.bannerKey!)).resolves.toBe(true);

      expect(video.posterKey).toBe(`posters/${id}.jpg`);
      expect(video.posterSource).toBe('AUTO');
      await expect(storage.exists('derived', video.posterKey!)).resolves.toBe(true);
    });

    /**
     * The poster is a 2:3 **crop** of the same frame, not a copy of the banner.
     *
     * Checked through the file size rather than by decoding: two JPEGs of
     * different dimensions from the same source cannot come out byte-identical,
     * and a crop filter that silently did nothing is exactly the failure this
     * catches.
     */
    it('cuts the poster to a different shape from the banner', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      media.enqueue(id);
      await media.drain();

      const banner = await readFile(storage.resolvePath('derived', `thumbnails/${id}.jpg`));
      const poster = await readFile(storage.resolvePath('derived', `posters/${id}.jpg`));

      expect(poster).not.toEqual(banner);
    });

    /**
     * The two sources move independently, which is the point of tracking them
     * separately: an admin picks a real poster for a film and still gets a fresh
     * banner out of the next probe.
     */
    it('regenerates the banner while leaving a MANUAL poster alone', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      media.enqueue(id);
      await media.drain();

      await admin.post(`/videos/${id}/poster/capture`).send({ atSeconds: 1 }).expect(200);
      const chosen = await readFile(storage.resolvePath('derived', `posters/${id}.jpg`));

      media.enqueue(id);
      await media.drain();

      const video = await prisma.video.findUniqueOrThrow({ where: { id } });
      expect(video.posterSource).toBe('MANUAL');
      expect(video.bannerSource).toBe('AUTO');

      const after = await readFile(storage.resolvePath('derived', `posters/${id}.jpg`));
      expect(after).toEqual(chosen);
    });

    // Into DERIVED_ROOT, never the watched tree — generated output landing
    // there would feed the ingest watcher its own work.
    it('writes it outside the media tree', async () => {
      await makeVideo('Films/bars.mp4');
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      media.enqueue(id);
      await media.drain();

      await expect(storage.exists('media', `thumbnails/${id}.jpg`)).resolves.toBe(false);
    });

    /**
     * Captures land atomically, or not at all.
     *
     * ffmpeg truncates its output the moment it opens it, so writing straight
     * to `thumbnails/<id>.jpg` left the live poster missing for as long as the
     * capture took — and every card in the app asks for that URL, so a routine
     * re-probe made artwork across the library flicker to a **404**, not merely
     * a stale picture. Three viewer tests caught it when a boot-time reconcile
     * re-probed everything mid-run.
     *
     * A failing capture is the observable half of that guarantee: the existing
     * poster has to come through it byte-for-byte.
     */
    it('leaves the existing poster intact when a capture fails part-way', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      await admin.post(`/videos/${id}/banner/capture`).send({ atSeconds: 1 }).expect(200);
      const before = await readFile(storage.resolvePath('derived', `thumbnails/${id}.jpg`));

      /*
       * Fails the way ffmpeg actually fails: it opens its output, truncates it,
       * writes some of a frame, and only then dies. A source ffmpeg cannot read
       * at all is not the same test — it never opens the output, so the live
       * poster survives even a direct write, and the mutation passes.
       */
      const ffmpeg = app.get(FfmpegService);
      const capture = jest
        .spyOn(ffmpeg, 'captureFrame')
        .mockImplementation(async (_source, _atSeconds, destination) => {
          await writeFile(destination, 'half a jpeg');
          throw new Error('ffmpeg died half way');
        });

      try {
        await admin.post(`/videos/${id}/banner/capture`).send({ atSeconds: 1 }).expect(500);
      } finally {
        capture.mockRestore();
      }

      const after = await readFile(storage.resolvePath('derived', `thumbnails/${id}.jpg`));
      expect(after.equals(before)).toBe(true);
    });

    /** A half-written frame must not be left where a later run could rename it in. */
    it('cleans up its temporary file when a capture fails', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      const ffmpeg = app.get(FfmpegService);
      const capture = jest
        .spyOn(ffmpeg, 'captureFrame')
        .mockImplementation(async (_source, _atSeconds, destination) => {
          await writeFile(destination, 'half a jpeg');
          throw new Error('ffmpeg died half way');
        });

      try {
        await admin.post(`/videos/${id}/banner/capture`).send({ atSeconds: 1 }).expect(500);
      } finally {
        capture.mockRestore();
      }

      await expect(storage.exists('derived', `tmp/${id}-banner.jpg`)).resolves.toBe(false);
    });

    /**
     * ffmpeg exits **0** when a seek lands past the end of a file.
     *
     * It prints "Output file is empty, nothing was encoded" and writes no file
     * at all, so a wrapper that trusts the exit code reports success and leaves
     * the *rename* to fail — surfacing as
     * `ENOENT ... rename derived/tmp/<id>-banner.jpg -> derived/thumbnails/<id>.jpg`,
     * which names neither the timestamp nor the file and reads like a storage
     * fault. Reported from a real library, where a poster was captured while a
     * 1 GB file was still being copied in.
     */
    it('says a frame could not be read, rather than failing on the rename', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      // 400, not 500: the admin picked a moment the file has nothing at, and
      // that is an answer about the request rather than a server fault.
      const response = await admin
        .post(`/videos/${id}/banner/capture`)
        .send({ atSeconds: 600 })
        .expect(400);

      const message = JSON.stringify(response.body);
      expect(message).not.toContain('ENOENT');
      expect(message).not.toContain('rename');
      expect(message).toMatch(/frame/i);
    });

    it('leaves no thumbnail behind when the frame could not be read', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      await admin.post(`/videos/${id}/banner/capture`).send({ atSeconds: 600 }).expect(400);

      await expect(storage.exists('derived', `thumbnails/${id}.jpg`)).resolves.toBe(false);
      await expect(storage.exists('derived', `tmp/${id}-banner.jpg`)).resolves.toBe(false);
    });

    /**
     * A poster is not the probe.
     *
     * `generateThumbnail` ran inside the probe's own try block, so a capture
     * that failed was written to `probeError` — on a row whose probe had just
     * succeeded and stored a duration, dimensions and codecs. The admin then
     * sees a file reported as broken in the ingest list while it plays and
     * edits perfectly well, which is exactly what was reported.
     */
    it('does not record a failed poster as a probe failure', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      const ffmpeg = app.get(FfmpegService);
      const capture = jest
        .spyOn(ffmpeg, 'captureFrame')
        .mockRejectedValue(new Error('no frame at that timestamp'));

      try {
        media.enqueue(id);
        await media.drain();
      } finally {
        capture.mockRestore();
      }

      const video = await prisma.video.findUniqueOrThrow({ where: { id } });
      // The probe itself worked, and its results are the point of the row.
      expect(video.probeError).toBeNull();
      expect(video.durationSec).toBeGreaterThan(0);
      expect(video.videoCodec).toBe('h264');
      // The poster simply is not there.
      expect(video.bannerKey).toBeNull();
    });

    /**
     * The invariant worth protecting: a poster someone chose by hand survives
     * a rescan. Losing it would mean losing an afternoon of curation to a
     * routine reprobe.
     */
    it('never overwrites a MANUAL thumbnail on a reprobe', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');
      await admin
        .post(`/videos/${id}/banner/capture`)
        .send({ atSeconds: 1 })
        .expect(200);
      const chosen = await readFile(storage.resolvePath('derived', `thumbnails/${id}.jpg`));

      await admin.post(`/videos/${id}/reprobe`).expect(200);

      const video = await prisma.video.findUniqueOrThrow({ where: { id } });
      expect(video.bannerSource).toBe('MANUAL');
      const after = await readFile(storage.resolvePath('derived', `thumbnails/${id}.jpg`));
      expect(after.equals(chosen)).toBe(true);
    });

    it('captures a frame at a chosen moment and marks it MANUAL', async () => {
      await makeVideo('Films/bars.mp4', { seconds: 2 });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      const response = await admin
        .post(`/videos/${id}/banner/capture`)
        .send({ atSeconds: 1 })
        .expect(200);

      expect(response.body).toMatchObject({ bannerSource: 'MANUAL' });
      await expect(storage.exists('derived', response.body.bannerKey)).resolves.toBe(true);
    });

    it('accepts an uploaded poster', async () => {
      await makeVideo('Films/bars.mp4');
      const id = await seedVideo('Films/bars.mp4', 'Bars');
      // A one-pixel PNG.
      const png = Buffer.from(
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
        'base64',
      );

      const response = await admin
        .post(`/videos/${id}/banner`)
        .attach('file', png, { filename: 'poster.png', contentType: 'image/png' })
        .expect(200);

      expect(response.body).toMatchObject({
        bannerKey: `thumbnails/${id}.png`,
        bannerSource: 'MANUAL',
      });
    });

    it('refuses an upload that is not an image a browser renders', async () => {
      await makeVideo('Films/bars.mp4');
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      await admin
        .post(`/videos/${id}/banner`)
        .attach('file', Buffer.from('#!/bin/sh'), { filename: 'evil.sh', contentType: 'text/x-sh' })
        .expect(400);
    });

    it('clearing returns the video to AUTO and removes the file', async () => {
      await makeVideo('Films/bars.mp4');
      const id = await seedVideo('Films/bars.mp4', 'Bars');
      media.enqueue(id);
      await media.drain();

      await admin.delete(`/videos/${id}/banner`).expect(204);

      const video = await prisma.video.findUniqueOrThrow({ where: { id } });
      expect(video).toMatchObject({ bannerKey: null, bannerSource: 'AUTO' });
      await expect(storage.exists('derived', `thumbnails/${id}.jpg`)).resolves.toBe(false);
    });
  });

  describe('reprobe endpoint', () => {
    it('fills in the fields and returns the updated video', async () => {
      await makeVideo('Films/bars.mp4', { size: '1920x1080' });
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      const response = await admin.post(`/videos/${id}/reprobe`).expect(200);

      expect(response.body).toMatchObject({ width: 1920, height: 1080, videoCodec: 'h264' });
    });

    it('is admin-only', async () => {
      await makeVideo('Films/bars.mp4');
      const id = await seedVideo('Films/bars.mp4', 'Bars');
      const invite = await admin.post('/admin/invites').send({}).expect(201);
      const user = request.agent(app.getHttpServer());
      await user
        .post('/auth/redeem')
        .send({ token: invite.body.token, username: 'grace', password: PASSWORD })
        .expect(201);

      await user.post(`/videos/${id}/reprobe`).expect(403);
      await user.delete(`/videos/${id}/banner`).expect(403);
      await user.post(`/videos/${id}/banner/capture`).send({ atSeconds: 0 }).expect(403);
    });

    it('404s an unknown video', async () => {
      await admin.post('/videos/nope/reprobe').expect(404);
    });
  });

  describe('the queue', () => {
    it('does not queue the same video twice', async () => {
      await makeVideo('Films/bars.mp4');
      const id = await seedVideo('Films/bars.mp4', 'Bars');

      media.enqueue(id);
      media.enqueue(id);
      media.enqueue(id);

      expect(media.pending).toBe(1);
      await media.drain();
    });

    it('gets through a batch', async () => {
      const ids: string[] = [];
      for (const name of ['a', 'b', 'c', 'd', 'e']) {
        await makeVideo(`Films/${name}.mp4`);
        ids.push(await seedVideo(`Films/${name}.mp4`, name.toUpperCase()));
      }

      ids.forEach((id) => media.enqueue(id));
      await media.drain();

      const probed = await prisma.video.count({ where: { probedAt: { not: null } } });
      expect(probed).toBe(5);
    });
  });

  describe('ingest queues probes for what it finds', () => {
    it('probes a newly ingested file end to end', async () => {
      await makeVideo('South Park/Season 01/01 - Pilot.mp4', { size: '1920x1080' });

      await admin.post('/admin/ingest/scan').expect(200);
      await media.drain();

      const video = await prisma.video.findFirstOrThrow({ where: { title: 'Pilot' } });
      expect(video).toMatchObject({ width: 1920, height: 1080, videoCodec: 'h264' });
      expect(video.bannerKey).not.toBeNull();
    });
  });
});
